### ISSUE TITLE
Get dataset and variable labels plus dataset keys when using versions of Define-XML v1.0

### ISSUE THREAD

**Issue by mhungria** [lexjansen/dataset-json-sas#14]
Unless I missed it in the slides or presentation, the dataset-json-sas package doesn't explicitly indicate the Define-XML versions supported.

Testing with Define-XML v1.0 for old actual data packages that I could use, the dataset-json-sas package was not retrieving dataset and variable labels plus dataset keys.

I made the following adjustments:
1. read_definexml.lua: dataset and variable labels plus dataset keys: different xpath to get the values without need to specify the Define-XML version.
2. 02_create_metadata_from_definexml.sas: manual update to populate the item key based on the item group retrieved keys, if item keys not already set.

Rationale for requesting the adjustment:
I assume there are old actual data packages that testers could use and adjusting the dataset-json-sas package for this purpose will allow for more testing (without the need to up-version the Define-XML document).
If the use case is considered convenient, I'll post the revisions after cross-checking with another set of data.

**Comment by lexjansen** [comment]
The Lua program has been updated to support Define-XML 1.0 (dataset and variable labels plus dataset keys).

**Comment by mhungria** [comment]
Thanks. I tested with your revisions to the Lua program and I got the same results as I did with the changes I had made.

**Comment by lexjansen** [comment]
Perfect. Thanks for testing. I will merge into the main branch. Let me know if there are more issues/wishes.
