### ISSUE TITLE
Requirements for JSON file?

### ISSUE THREAD

**Issue by dditomma** [lexjansen/dataset-json-sas#24]
I think this code enforces some requirements for JSON structure, limiting scope of JSON files that the code can parse and translate to a SAS data set.

- https://github.com/lexjansen/dataset-json-sas/blob/master/macros/read_datasetjson.sas#L93

Fine, since the name "dataset-json" makes this at least implicit. It would be helpful if the top-level README makes this explicit. If I understand correctly, JSON is a generic container, and one JSON could include multiple, complex, nested, etc. data structures. I don't think that such flexibility is the intention of this "dataset-json" project, and not surprisingly the code fails for out-of-scope JSON structures that represent more than a single SAS table structure. All fair enough, and similar to our restricted typical use of "xpt" containers for a single SAS data set.

Rather than "a SAS implementation for converting Dataset-JSON files to and from SAS datasets", does this project have a narrower scope - specifically with a single SAS dataset in mind:

- a SAS implementation to convert a SAS dataset to and from a Dataset-JSON file, single SAS data set structure.

?

This would more clearly limit the scope to JSON structure directly translatable to/from a SAS data structure.

**Comment by lexjansen** [comment]
Thanks for the feedback. I should make it more clear that this code is an implementation of the CDISC Dataset-JSON specification: https://www.cdisc.org/dataset-json
This specification only allows one dataset per JSON file:: "Dataset-JSON must contain only one dataset per file."

**Comment by lexjansen** [comment]
Yes, I need to do more messaging to the user. If one of these macro variables is null after processing the JSON file, I should stop with a message:
_clinicalreferencedata_ _items_ _itemdata_ _itemgroupdata_ ItemGroupOID _ItemGroupName
Thanks!

**Comment by lexjansen** [comment]
I added error messages when the macro variables clinicalreferencedata, items, itemdata, or itemgroupdata are still empty after their definition.
