### ISSUE TITLE
add support for SEND

### ISSUE THREAD

**Issue by wangw106** [lexjansen/dataset-json-sas#28]
I am using this code to convert SEND dataset (with define file) to Dataset-Json. I am not a SAS programmer, but able to copy/paste then modify the STDM code to support SEND. Do you think I should merge in the code with SEND support? The changes will be for those SAS files under programs folder, plus create folders for send. Thanks.

**Comment by lexjansen** [comment]
Hi,
Great it works for you!
Feel free to do a PR with SEND examples.
The macros are not really SEND, ADaM, or SDTM specific.
Actually it works with any tabular standard.
The programs just demonstrate the macros.
Thanks.
Lex

**Comment by lexjansen** [comment]
If you like, you can do a PR with just your XPT data and Define-XMl file in data/send_xpt, and I can take care of the rest.

**Comment by wangw106** [comment]
[SEND_Study1.zip](https://github.com/lexjansen/dataset-json-sas/files/14532105/SEND_Study1.zip)

Great, I attached a SEND study with define file here.
A second question, when I read the dataset-json generated in R, I got a Warning message: In readLines(file):  incomplete final line found on .... 
Is it necessary to add a new line at the end of the json file?
Aside from this, the macros works great for SEND files.

Thanks,

**Comment by lexjansen** [comment]
Thanks!
I’m not sure about the error.
The JSON SAS creates is just one long string.
I will look into that.
Do you use https://github.com/atorus-research/datasetjson ?

**Comment by lexjansen** [comment]
Just to be sure - this is not confidential data, right?

**Comment by wangw106** [comment]
> Just to be sure - this is not confidential data, right?

Correct, this is not confidential data. This is a SEND package from CBER pilot.

**Comment by wangw106** [comment]
> Thanks! I’m not sure about the error. The JSON SAS creates is just one long string. I will look into that. Do you use https://github.com/atorus-research/datasetjson ?

Yes, that is the package I used to read the json file. It is not an error, it is just a warning. The one long string looks correct. I am just wondering that if SAS writes this long string to a json file, is it necessary to add a new line at the end.

**Comment by lexjansen** [comment]
Excellent!

**Comment by lexjansen** [comment]
I added SEND in the new branch: https://github.com/lexjansen/dataset-json-sas/tree/github_issue_28_send
Also, I updated the stylesheet with the latest one (2018, see: https://wiki.cdisc.org/display/PUB/Stylesheet+Library).
The one that was used was very outdated.

**Comment by wangw106** [comment]
> I added SEND in the new branch: https://github.com/lexjansen/dataset-json-sas/tree/github_issue_28_send Also, I updated the stylesheet with the latest one (2018, see: https://wiki.cdisc.org/display/PUB/Stylesheet+Library). The one that was used was very outdated. Let me know if you have any comments. If not, then I will merge into main.

Thanks. A question about attribute name used for SEND, this may be a Dataset-JSON specification question:
In the top level, the specification has "clinicalData" and "referenceData" attribute. It is understandable that SDTM and ADAM use "clinicalData - Contains datasets for clinical data across multiple subjects". With SEND added, should we still use clinicalData? Or a new attribute like "nonclinicalData - Contains datasets for nonclinical data across multiple subjects".

**Comment by lexjansen** [comment]
Yes, that is a good comment. You would still use clinicalData.
There has been a lot of feedback from the pilots.
This is one of the things we will address.

**Comment by wangw106** [comment]
> Yes, that is a good comment. You would still use clinicalData. The macro makes the determination based on whether the dataset contains a usubjid variable. There has been a lot of feedback from the pilots. This is one of the things we will address.

Thanks for your quick reply, to my comment and to my request. I don't have any more comments about the branch, you can merge into main.
