### ISSUE TITLE
Question about length of date/time datatype variable.

### ISSUE THREAD

**Issue by MinJi-Yi** [lexjansen/dataset-json-sas#30]
I have a question about length of date/time datatype variable.

According to the define.xml, the length attribute must be empty when datatype is not integer, float, or text. (Rule ID: DD0068)
But, according to the "CDISC_COSA_webinar_20231005_dataset-json_SAS" slide, the length of ISO8601 formatted data in json file has string datatype and is assigned length. 
Is j-son more similar to dataset than define.xml?
I want to know why the length should be assigned in json file.
As you know, it is taken from dataset and it requires more work.

**Comment by lexjansen** [comment]
Hi,
length is an optional attribute. Dataset-JSON does not need it.

**Comment by MinJi-Yi** [comment]
Hi,
As length attribute is optional requirement, I understand I can drop the attribute. 
Thank you for the reply.
