### ISSUE TITLE
Question about macro variable in nested code

### ISSUE THREAD

**Issue by MinJi-Yi** [lexjansen/dataset-json-sas#31]
Hi, 
I run the code using call execute. The 1st code run occurs errors, because  dset_id variable has the value 0. But, 2nd run has no issue.
How can I fix it?

Thank you in advace.
MinJi

**Comment by lexjansen** [comment]
Hi, which program are you running and can you show the log, with mprint, mlogic, symbolgen.

**Comment by MinJi-Yi** [comment]
> Hi, which program are you running and can you show the log, with mprint, mlogic, symbolgen.

Hi, when I ran write_datasetjson.sas and execute  %write_json_metadata_array(work.column_metadata), I got the error.

**Comment by lexjansen** [comment]
dset_id is created opening the dataset. Without a full log it is hard for me to know what is going on.

**Comment by MinJi-Yi** [comment]
Hi, I resolved the error. Thanks.
