### ISSUE TITLE
CreateMetadataFromDefineXML macro

### ISSUE THREAD

**Issue by Dipal88** [lexjansen/dataset-json-sas#33]
code does not work of CreateMetadataFromDefineXML if define file version is 2.0

**Comment by lexjansen** [comment]
Please add detail, including a Define-XML 2.0 file.

**Comment by lexjansen** [comment]
@Dipal88 Do you have any more details?

**Comment by Dipal88** [comment]
Hi,

Sorry for the late reply.

Actually I tried the whole code for prepared CDISC package with define 2.0.
but that macro did not work. As you said to give more details, I have to
re-run with another project and check if it is working or not.  Give me
some time . I will reply.

Thank you for the patience.

Thank you.

Dipal Modi

**Comment by lexjansen** [comment]
Thank you.

**Comment by lexjansen** [comment]
I downloaded one of the releases from [https://github.com/lexjansen/dataset-json-sas/releases](https://github.com/lexjansen/dataset-json-sas/releases).
Both will work.

I used the Define-XML file from https://www.cdisc.org/standards/data-exchange/define-xml/define-xml-v2-0
with the following code:

```
%* update this location to your own location;
%let project_folder=/_github/lexjansen/dataset-json-sas-1.0;
%include "&project_folder/programs/config.sas";

libname meta "&project_folder/test";

/* Create metadata from Define-XML for SDTM */
%CreateMetadataFromDefineXML(
   definexml=&project_folder/test/define2-0-0-example-sdtm.xml,
   metadatalib=meta
   );
```

It ran without issues. 
I will be happy to help.

**Comment by lexjansen** [comment]
Hi,
Did you ever get around to this and replicate the issue?
Thanks,
Lex
