### ISSUE TITLE
Question ("03-update-metadata.sas"): rationality for setting decimal dataType in the case of ADaM datasets?

### ISSUE THREAD

**Issue by mhungria** [lexjansen/dataset-json-sas#36]
Could you please comment on the rationality you followed for assigning dataType="decimal" in "03-update-metadata.sas" just to the following?

<img width="1048" alt="image" src="https://github.com/user-attachments/assets/4a9afd57-9095-4066-8a90-6a477cc5253b">

**Comment by lexjansen** [comment]
It is just an example as written in the lines above the code you show.:
```
  /* Define-XML v2 does not support decimal, but it is supported by Dataset-JSON. */
  /* This update is just to show that it works in Dataset-JSON. */

```
Users can read more about Dataset-JSON and the decimal dataType at: [https://wiki.cdisc.org/display/DSJSON1DOT1/Precision+and+Rounding](https://wiki.cdisc.org/display/DSJSON1DOT1/Precision+and+Rounding)
