### ISSUE TITLE
Format missing for numeric dates when displayFormat attributes not used

### ISSUE THREAD

**Issue by cpiraux** [lexjansen/dataset-json-sas#39]
I tested a scenario where a dataset-JSON is created from an R dataframe without providing any metadata. In this case, display formats are not included in the dataset-JSON. When converting this dataset-JSON to a SAS dataset, there is no format applied to numeric date values. Would it be possible to implement a default format for date, time, and datetime for numeric date(time) values, as these formats may not always be present in the dataset-JSON?

![image](https://github.com/user-attachments/assets/7715369a-a4d9-446f-87b1-cc4ff8a0cf59)

![image](https://github.com/user-attachments/assets/6c24392e-2014-4f5d-bcd3-c5f6b02d902c)

**Comment by lexjansen** [comment]
Thanks! I will add ISO 8601 formats, when displayFormat is not defined.

**Comment by cpiraux** [comment]
Thanks for adding a default format.

What I meant by 'no metadata' was more about user metadata. It's possible to programmatically identify the date(time) variable in an R dataframe, but it's not possible to add a DisplayFormat without user input since there is no DisplayFormat in the dataframe.

**Comment by lexjansen** [comment]
This is fixed and merged into master.

**Comment by cpiraux** [comment]
Thanks, Lex, for the update!
I reran read_json with the programs from the branch, and it looks good to me.
