### ISSUE TITLE
Issue when length attribute not included in Dataset-JSON

### ISSUE THREAD

**Issue by cpiraux** [lexjansen/dataset-json-sas#40]
I tested two scenarios related to length attributes:

1. In the first scenario, I converted a dataset-JSON to a SAS dataset with the length attributes completely missing. In this case, some errors appeared in the log.
2. In the second scenario, I specified the length attribute for only one variable. The macro ran successfully, but an extra variable for ITEMGROUPDATASEQ was present in the SAS dataset.

**Scenario 1: Error in the log**
![image](https://github.com/user-attachments/assets/73639e4f-4fc5-41b8-9b0f-0b91fe303518)
![image](https://github.com/user-attachments/assets/9c2393c7-a7c9-4cb7-a511-541e4c4f06f6)

**Scenario 2: Extra variable in the dataset**

![image](https://github.com/user-attachments/assets/481bd867-8b10-4886-b886-c8ece287dae5)

**Comment by lexjansen** [comment]
Thanks. Yes, I need to check when there are no lengths defined.
For the ITEMGROUPDATASEQ, did you specify dropseqvar=Y or dropseqvar=N?

**Comment by cpiraux** [comment]
Thanks for your feedback!

I reran my code, and now ITEMGROUPDATASEQ is not present. Dropseqvar was already set to 'Y'. I am not able to reproduce this issue, so I probably made an incorrect manipulation :thinking:.

**Comment by lexjansen** [comment]
This is fixed and merged into master.

**Comment by cpiraux** [comment]
Thanks, Lex, for the update!
I reran read_json with the programs from the branch, and it looks good to me.
