### ISSUE TITLE
Value truncated for non-ASCII character

### ISSUE THREAD

**Issue by cpiraux** [lexjansen/dataset-json-sas#41]
I tested the `read_datasetjson` macro with a dataset-JSON containing non-ASCII characters. In the dataset-JSON, the length was defined as the number of characters. In the resulting SAS dataset, the value was truncated.

![image](https://github.com/user-attachments/assets/af0f5b16-082c-47fc-86d6-d9b8d8110eea)
![image](https://github.com/user-attachments/assets/ad40b38e-574d-49da-b253-390c93b32880)

Log 
![image](https://github.com/user-attachments/assets/749d1e39-87b5-44c8-b556-3a4642523a97)

Dataset
![image](https://github.com/user-attachments/assets/893a743e-ab4d-411c-b63a-50abe5a4d27f)

**Comment by lexjansen** [comment]
Thanks, Celine, what was the encoding of your session?

**Comment by cpiraux** [comment]
The encoding of the session is UTF-8. 

The value becomes truncated after this piece of code; before that, the value is complete.
![image](https://github.com/user-attachments/assets/41a15231-36d1-4921-ada2-fee1d32766ed)

The assigned length is from the Dataset-JSON (length=14), which corresponds to the number of characters. However, the length should be 40 bytes to avoid truncating the value.
![image](https://github.com/user-attachments/assets/215eb8e1-d0b6-4134-84e7-e1b4afb5203d)

**Comment by lexjansen** [comment]
I compare the length from Dataset-JSON (14) with the length set by the JSON libname engine. In this case the Dataset-JSON length is smaller, so it would not be used to change the length.
But I will further investigate.
Thank you for your testing. Very much appreciated!

**Comment by lexjansen** [comment]
I can not replicate this issue. 
I used attached Dataset-JSON file that has non-ASCII characters in AETERM. I also set the length of AETERM to 15. 
[ae_utf8.json](https://github.com/user-attachments/files/16614108/ae_utf8.json)

In the log AETERM will not be part of the length statement, since the length in the Dataset-JSON file is shorter than the length in the created dataset:

```
MPRINT(READ_DATASETJSON):   proc sql noprint;
MPRINT(READ_DATASETJSON):   select catt(d.name, ' $', i.length) into :length separated by ' ' from dictionary.columns d, out_0884.columns i where upcase(libname)="OUT" and upcase(memname)="AE" and d.name = i.name and d.type="char" and 
(not(missing(i.length))) and (i.length gt d.length) ;
MPRINT(READ_DATASETJSON):   quit ;
NOTE: PROCEDURE SQL used (Total process time):
      real time           0.00 seconds
      cpu time            0.01 seconds
      

MPRINT(READ_DATASETJSON):   data out.AE( label = "Adverse Events" DROP=ITEMGROUPDATASEQ );
MPRINT(READ_DATASETJSON):   retain ITEMGROUPDATASEQ STUDYID DOMAIN USUBJID AESEQ AESPID AETERM AELLT AELLTCD AEDECOD AEPTCD AEHLT AEHLTCD AEHLGT AEHLGTCD AEBODSYS AEBDSYCD AESOC AESOCCD AESEV AESER AEACN AEREL AEOUT AESCAN AESCONG AESDISAB AESDTH AESHOSP 
AESLIFE AESOD AEDTC AESTDTC AEENDTC AESTDY AEENDY AETRTEM;
MPRINT(READ_DATASETJSON):   length AELLT $100 AEDECOD $200 AEHLT $100 AEHLGT $100 AEBODSYS $67 AESOC $100 AEACN $30 AEOUT $200;
MPRINT(READ_DATASETJSON):  ;
MPRINT(READ_DATASETJSON):   set out.AE;
MPRINT(READ_DATASETJSON):   run;

```
Later in the LOG I will get  the following - expected - message:

```
MPRINT(READ_DATASETJSON):   set column_metadata;
MPRINT(READ_DATASETJSON):   if DataType="char" and not (type in ('string' 'datetime' 'date' 'time')) then putlog "WAR" "NING: [READ_DATASETJSON] TYPE ISSUE: dataset=datalib..AE " OID= name= DataType= type=;
MPRINT(READ_DATASETJSON):   if DataType="num" and not (type in ('integer' 'double' 'float' 'decimal' 'datetime' 'date' 'time')) then putlog "WAR" "NING: [READ_DATASETJSON] TYPE ISSUE: dataset=datalib..AE " OID= name= DataType= type=;
MPRINT(READ_DATASETJSON):   if DataType="char" and not(missing(length)) and (length lt sas_length) then putlog "WAR" "NING: [READ_DATASETJSON] LENGTH ISSUE: dataset=datalib..AE " OID= name= length= sas_length=;
MPRINT(READ_DATASETJSON):   run;

WARNING: [READ_DATASETJSON] LENGTH ISSUE: dataset=datalib..AE OID=IT.AE.AETERM name=AETERM length=15 sas_length=45

```

Would you mind sharing the dataset-JSON file that is giving you the issue?

**Comment by cpiraux** [comment]
I've tested ae_utf8.json in my program and got the same log as you. 

The issue might be related to the JSON file I used: 
[adae_utf8.json](https://github.com/user-attachments/files/16622013/adae_utf8.json)

**Comment by lexjansen** [comment]
I found the issue. It was not even specific for NON-ASCII. In the `read_datasetjson` version before I made fixes yesterday, there was a 'rogue' proc sql statement:
```
    select catt(name, ' $', length) into :length separated by ' '
      from out_&_Random..&_items_
      where datatype="string" and (not(missing(length)));

```
This selected all variable lengths from the imported Dataset-JSON file. This macro generated `length` macro variable was never used.
Further in the program I had the following code:
```
    proc sql noprint;
      select catt(d.name, ' $', i.length) into :length separated by ' '
        from dictionary.columns d,
             out_&_Random..&_items_ i
      where upcase(libname)="%upcase(&datalib)" and
           upcase(memname)="%upcase(&dsname)" and
           d.name = i.name and
           d.type="char" and (not(missing(i.length))) and (i.length gt d.length)
     ;
    quit ;
```
Since this did not select any rows in your example, and the `length` macro variable was not initialized (!), the earlier created `length` macro vcariable was used (with AESER $14):

```
MPRINT(READ_DATASETJSON):   data out.ADAE( label = "Adverse Events Analysis Dataset" DROP=ITEMGROUPDATASEQ );
MPRINT(READ_DATASETJSON):   retain ITEMGROUPDATASEQ STUDYID SITEID USUBJID TRTA TRTAN AGE AGEGR1 AGEGR1N RACE RACEN SEX SAFFL TRTSDT TRTEDT ASTDT ASTDTF ASTDY AENDT AENDY ADURN ADURU AETERM AELLT AELLTCD AEDECOD AEPTCD AEHLT AEHLTCD AEHLGT AEHLGTCD 
AEBODSYS AESOC AESOCCD AESEV AESER AESCAN AESCONG AESDISAB AESDTH AESHOSP AESLIFE AESOD AEREL AEACN AEOUT AESEQ TRTEMFL AOCCFL AOCCSFL AOCCPFL AOCC02FL AOCC03FL AOCC04FL CQ01NAM AOCC01FL;
MPRINT(READ_DATASETJSON):   length STUDYID $12 SITEID $3 USUBJID $11 TRTA $20 AGEGR1 $5 RACE $32 SEX $1 SAFFL $1 ASTDTF $1 ADURU $3 AETERM $46 AELLT $46 AEDECOD $46 AEHLT $8 AEHLGT $9 AEBODSYS $67 AESOC $67 AESEV $8 AESER $14 AESCAN $1 AESCONG $1 AESDISAB 
$1 AESDTH $1 AESHOSP $1 AESLIFE $1 AESOD $1 AEREL $8 AEACN $1 AEOUT $26 TRTEMFL $1 AOCCFL $1 AOCCSFL $1 AOCCPFL $1 AOCC02FL $1 AOCC03FL $1 AOCC04FL $1 CQ01NAM $19 AOCC01FL $1;
MPRINT(READ_DATASETJSON):   format TRTSDT DATE9. TRTEDT DATE9. ASTDT DATE9. AENDT DATE9.;
MPRINT(READ_DATASETJSON):   set out.ADAE;
MPRINT(READ_DATASETJSON):   run;

WARNING: Multiple lengths were specified for the variable AESER by input data set(s). This can cause truncation of data.

```

This was already fixed with issue 40, and I did some further cleanup and tightening of the code, which has been merged to master. Let me know if you still have issues.

This is the dataset with the updated macro:
![image](https://github.com/user-attachments/assets/a9d850b4-af38-4c94-a7e9-c1598d0d13cc)
![image](https://github.com/user-attachments/assets/eec286cd-71bc-42ff-8cad-ff64caf22eff)

**Comment by cpiraux** [comment]
Thanks, Lex, for investigating the issue and finding the cause!
I reran read_json with the programs from the branch, and it looks good to me!
