### ISSUE TITLE
create_metadata_from_definexml fails where define.xml contains a single ItemGroupDef

### ISSUE THREAD

**Issue by ASL-rmarshall** [lexjansen/dataset-json-sas#48]
When the define.xml file only contains a single ItemGroupDef, the` create_metadata_from_definexml` macro fails with the following error:

```
ERROR: C:\CDISC\dataset-json-sas\lua\read_definexml.lua:96: bad argument #1 to 'ipairs' (table expected, got nil)
stack traceback:
	[C]: in function 'ipairs'
	C:\CDISC\dataset-json-sas\lua\read_definexml.lua:96: in main chunk
	[C]: in function '_G.require
```

**Comment by ASL-rmarshall** [comment]
The error occurs because the structure of `define.Study.MetaDataVersion.ItemGroupDef` in `read_definexml.lua` is not the same when there is 1 ItemGroupDef vs multiple.

**Comment by lexjansen** [comment]
Good catch! I can fix that today.

**Comment by ASL-rmarshall** [comment]
Zip file with updated .lua files: [read_definexml.zip](https://github.com/user-attachments/files/17480131/read_definexml.zip)
